services:
    downloadapp.scanners.deviantart.scanner:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\Scanner
        arguments:
            - '@downloadapp.scanners.deviantart.api'
            - '@csa_guzzle.client.general'
            - '@downloadapp.user.current'
            - '@downloadapp.downloads'
            - '@downloadapp.scanners.deviantart.scheduler'
            - '@downloadapp.utils.notifications'

    downloadapp.scanners.deviantart.api:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\ApiProvider
        arguments:
            - '%deviantart.authentication.id%'
            - '%deviantart.authentication.secret%'
            - '%deviantart.authentication.redirectUri%'
            - '@downloadapp.scanners.deviantart.tokens.user'

    downloadapp.scanners.deviantart.tokens.simple:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\SimpleFileTokenProvider
        arguments:
            - '%deviantart.simpleToken.filename%'

    downloadapp.scanners.deviantart.tokens.user:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\UserTokenProvider
        arguments:
            - '%deviantart.userToken.directory%'
            - '@downloadapp.user.current'
            - '@downloadapp.utils.path'

    downloadapp.scanners.deviantart.contractor:
        class: DownloadApp\Scanners\DeviantArtBundle\Contractor\Contractor
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@downloadapp.user.current'
            - '@downloadapp.scanners.deviantart.scheduler'
        tags:
            - name: downloadapp.contractor
              priority: 25

    downloadapp.scanners.deviantart.scheduler:
        class: DownloadApp\Scanners\CoreBundle\Service\ScanScheduler
        arguments:
            - '@downloadapp.user.current'
            - '@doctrine.orm.entity_manager'
            - !php/const:\DownloadApp\Scanners\DeviantArtBundle\Command\ScanCommand::NAME
            - !php/const:\DownloadApp\Scanners\DeviantArtBundle\Command\WatchlistCommand::NAME
            - !php/const:\DownloadApp\Scanners\DeviantArtBundle\Service\Scanner::QUEUE
