services:
    downloadapp.scanners.deviantart.scanner:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\Scanner
        arguments:
            - '@downloadapp.scanners.deviantart.api'
            - '@csa_guzzle.client.general'
            - '@doctrine.orm.entity_manager'
            - '@downloadapp.user.current'
            - '@downloadapp.download'

    downloadapp.scanners.deviantart.api:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\ApiProvider
        arguments:
            - '%deviantart.authentication.id%'
            - '%deviantart.authentication.secret%'
            - '%deviantart.authentication.redirectUri%'
            - '@downloadapp.scanners.deviantart.tokens.user'

    downloadapp.scanners.deviantart.tokens.simple:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\SimpleFileTokenProvider
        arguments:
            - '%deviantart.simpleToken.filename%'

    downloadapp.scanners.deviantart.tokens.user:
        class: DownloadApp\Scanners\DeviantArtBundle\Service\UserTokenProvider
        arguments:
            - '%deviantart.userToken.directory%'
            - '@downloadapp.user.current'
            - '@downloadapp.utils.path'
