imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        path: '%database_path%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

user:
    cookiejars:
        furaffinity:
            directory: '%kernel.project_dir%/var/cookies/furaffinity'
        weasyl:
            directory: '%kernel.project_dir%/var/cookies/weasyl'

csa_guzzle:
    clients:
        general:
            config:
                headers:
                    User-Agent: '%user_agent%'
                    Accept-Encoding: '*'
        furaffinity:
            config:
                cookies: '@downloadapp.user.cookiejars.furaffinity'
                headers:
                    User-Agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.89 Chrome/62.0.3202.89 Safari/537.36'
                    Accept-Encoding: '*'
        weasyl:
            config:
                cookies: '@downloadapp.user.cookiejars.weasyl'
                headers:
                    User-Agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.89 Chrome/62.0.3202.89 Safari/537.36'
                    Accept-Encoding: '*'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

deviantart:
    authentication:
        id: '%deviantart_id%'
        secret: '%deviantart_secret%'
        redirectUri: '%base_url%/deviantart/authorize'
    simpleToken:
        filename: '%kernel.project_dir%/var/deviantart_token.json'
    userToken:
        directory: '%kernel.project_dir%/var/tokens/deviantart'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: DownloadApp\App\UserBundle\Entity\User
    from_email:
      address: '%registration_mail%'
      sender_name: '%registration_sender%'

jms_job_queue:
    queue_options_defaults:
        max_concurrent_jobs: 3
    queue_options:
        scanners.deviantart:
            max_concurrent_jobs: 1
        scanners.furaffinity:
            max_concurrent_jobs: 4
