frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

scanner_core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /scanners

weasyl:
    resource: "@WeasylBundle/Resources/config/routing.yml"
    prefix:   /scanners/weasyl

fur_affinity:
    resource: "@FurAffinityBundle/Resources/config/routing.yml"
    prefix:   /scanners/furaffinity

deviantart:
    resource: "@DeviantArtBundle/Resources/config/routing.yml"
    prefix:   /scanners/deviantart

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

benkle_notifications:
    resource: "@BenkleNotificationBundle/Resources/config/routing.yml"
    prefix: /
