frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

fur_affinity:
    resource: "@FurAffinityBundle/Resources/config/routing.yml"
    prefix:   /furaffinity

deviantart:
    resource: '@DeviantArtBundle/Resources/config/routing.yml'
    prefix: /deviantart

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
