services:
    downloadapp.download.remote_file:
        class: DownloadApp\App\DownloadBundle\Entity\RemoteFile
        tags:
            - name: benkle.doctrine.adoption.child
              of: DownloadApp\App\DownloadBundle\Entity\File
              discriminator: remote_file

    downloadapp.download.content_file:
        class: DownloadApp\App\DownloadBundle\Entity\ContentFile
        tags:
            - name: benkle.doctrine.adoption.child
              of: DownloadApp\App\DownloadBundle\Entity\File
              discriminator: content_file

    downloadapp.download.content_file_download_service:
        class: DownloadApp\App\DownloadBundle\Service\ContentFileDownloadService
        tags:
            - name: downloadapp.file_download_service
              for: DownloadApp\App\DownloadBundle\Entity\ContentFile

    downloadapp.download.remote_file_download_service:
        class: DownloadApp\App\DownloadBundle\Service\RemoteFileFileDownloadService
        tags:
            - name: downloadapp.file_download_service
              for: DownloadApp\App\DownloadBundle\Entity\RemoteFile
        arguments:
            - "@csa_guzzle.client.general"

    downloadapp.download:
      class: DownloadApp\App\DownloadBundle\Service\DownloadService
      arguments:
          - "@doctrine.orm.entity_manager"
          - ~
