services:
    downloadapp.download.file.remote:
        class: DownloadApp\App\DownloadBundle\Entity\RemoteFile
        tags:
            - name: benkle.doctrine.adoption.child
              of: DownloadApp\App\DownloadBundle\Entity\File
              discriminator: remote_file

    downloadapp.download.file.content:
        class: DownloadApp\App\DownloadBundle\Entity\ContentFile
        tags:
            - name: benkle.doctrine.adoption.child
              of: DownloadApp\App\DownloadBundle\Entity\File
              discriminator: content_file

    downloadapp.download.filedownloader.content:
        class: DownloadApp\App\DownloadBundle\Service\ContentFileDownloader
        tags:
            - name: downloadapp.file.downloader
              for: DownloadApp\App\DownloadBundle\Entity\ContentFile
        calls:
            - method: setPathUtils
              arguments:
                  - '@downloadapp.utils.path'

    downloadapp.download.file.downloader.remote:
        class: DownloadApp\App\DownloadBundle\Service\RemoteFileFileDownloader
        tags:
            - name: downloadapp.file.downloader
              for: DownloadApp\App\DownloadBundle\Entity\RemoteFile
        arguments:
            - "@csa_guzzle.client.general"
        calls:
            - method: setPathUtils
              arguments:
                  - '@downloadapp.utils.path'

    downloadapp.download:
        class: DownloadApp\App\DownloadBundle\Service\Downloads
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@downloadapp.user.filesystem"
