services:
    downloadapp.scanners.furaffinity.scanner:
        class: DownloadApp\Scanners\FurAffinityBundle\Service\Scanner
        arguments:
            - '@csa_guzzle.client.furaffinity'
            - '@doctrine.orm.entity_manager'
            - '@downloadapp.user.current'
            - '@downloadapp.download'
            - '@downloadapp.utils.path'
            - '@event_dispatcher'

    downloadapp.scanners.furaffinity.contractor:
        class: DownloadApp\Scanners\FurAffinityBundle\Contractor\Contractor
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@downloadapp.user.current'
        tags:
            - name: downloadapp.contractor
              priority: 25
