services:
    downloadapp.scanners.furaffinity.scanner:
        class: DownloadApp\Scanners\FurAffinityBundle\Service\Scanner
        arguments:
            - '@csa_guzzle.client.furaffinity'
            - '@doctrine.orm.entity_manager'
            - '@downloadapp.user.current'
            - '@downloadapp.download'
            - '@downloadapp.utils.path'
            - '@downloadapp.scanners.furaffinity.scheduler'
            - '@downloadapp.utils.notifications'

    downloadapp.scanners.furaffinity.contractor:
        class: DownloadApp\Scanners\FurAffinityBundle\Contractor\Contractor
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@downloadapp.user.current'
        tags:
            - name: downloadapp.contractor
              priority: 25

    downloadapp.scanners.furaffinity.scheduler:
        class: DownloadApp\Scanners\CoreBundle\Service\ScanScheduler
        arguments:
            - '@downloadapp.user.current'
            - '@doctrine.orm.entity_manager'
            - !php/const:\DownloadApp\Scanners\FurAffinityBundle\Command\ScanCommand::NAME
            - !php/const:\DownloadApp\Scanners\FurAffinityBundle\Service\Scanner::QUEUE
