services:
    downloadapp.scanners.furaffinity.scanner:
        class: DownloadApp\Scanners\FurAffinityBundle\Service\Scanner
        arguments:
            - '@csa_guzzle.client.furaffinity'
            - '@doctrine.orm.entity_manager'
            - '@downloadapp.user.current'
            - '@downloadapp.download'
            - '@downloadapp.utils.path'
            - '@event_dispatcher'
